language: node_js
sudo: false
notifications:
  email: false
script:
  - ./script/setup
  - ./script/build
  - ./script/test
after_script:
  # Report coverage to codecov
  - bash <(curl -s https://codecov.io/bash)
