language: node_js
node_js:
  - 10

sudo: false
notifications:
  email: false
before_install:
  - nvm install $(cat .node-version)
install:
  - ./script/setup
script:
  - ./script/build
  - ./script/test
after_script:
  # Report coverage to codecov
  - bash <(curl -s https://codecov.io/bash)
