#!/bin/bash

echo "==> Initializing nvm"
echo "nvm: $(nvm --version)"

if [[ -d "./script/" ]]; then
  ./script/setup || exit 2
  ./script/build || exit 3
fi

# The styleguides should now be in `./styleguide/`

# Upload the files so they can be viewed
# Use the build id for the directory name

# ###
# Send
# ###

remote_user="rundeck"
remote_host="packages.cnx.org"
remote_dir="/var/www/repo/pattern-library/${GIT_COMMIT}/"
latest_dir="/var/www/repo/pattern-library/latest/"
local_styleguide_dir="./styleguide/"

# shellcheck disable=SC2029
ssh ${remote_user}@${remote_host} "mkdir -p '${remote_dir}'" || exit 5
rsync -avp -e "ssh -l${remote_user}" ${local_styleguide_dir} ${remote_host}:"${remote_dir}" || exit 6

if [[ "${GIT_BRANCH}" == "origin/master" ]]; then
  rsync -avp -e "ssh -i -l${remote_user}" ${local_styleguide_dir} ${remote_host}:${latest_dir} || exit 6
fi
# ssh -i ${key_path} ${remote_user}@${remote_host} "cd ${remote_dir} && tar -xvzf '${remote_dir}/${tarball}'"


# TODO: Use the uploaded URL in the CI status message
