#!/bin/bash
cd "$(dirname "$0")/.." || exit 111
source ./script/bootstrap || exit 111

$(npm bin)/sass-lint -c sass-lint.yml -v -q || exit $?
npm run kss
mkdir -p styleguide/core
$(npm bin)/sass core/pattern-library.scss > styleguide/core/pattern-library.css
cat <<.
Now load styleguide/index.html in your browser
.
