#!/bin/bash
cd "$(dirname "$0")/.." || exit 111
source ./script/bootstrap || exit 111

do_progress_quiet "Running KSS to build styleguide" \
  npm run-script kss

try mkdir -p styleguide/core

do_progress_quiet "Compiling SASS file for styleguide" \
  $(npm bin)/sass ./core/pattern-library.scss ./styleguide/core/pattern-library.css

echo "Now load styleguide/index.html in your browser"
