#!/bin/bash
cd "$(dirname "$0")/.." || exit 111
source ./script/bootstrap || exit 111

rm ./*.lcov
for fn in styleguide/*.html; do
  nodir=$(basename -- "$fn")
  noext="${nodir%.*}"
  do_progress_quiet "Testing $fn" \
    npm run-script test2 -- --html "$fn" --lcov "./$noext.lcov" || echo "Failed in $noext"
done

# Validate the shell scripts
if [[ $(command -v shellcheck) ]]; then
  # shellcheck disable=SC2046
  do_progress_quiet "Linting shell scripts" \
    shellcheck $(find ./script  -mindepth 1 -maxdepth 1 -not -path '*/\.*' -type f)
fi
