#!/bin/bash
cd "$(dirname "$0")/.." || exit 111
source ./script/bootstrap || exit 111

if [ -d ./coverage ]; then
  rm -f ./coverage/*
else
  mkdir ./coverage
fi
for fn in styleguide/*.html; do
  nodir=$(basename -- "$fn")
  noext="${nodir%.*}"
  do_progress_quiet "Testing $fn" \
    npm run-script test2 -- --html "$fn" --lcov "./coverage/$noext.lcov"
done
