---
jobs:
  pattern-library:
    runs-on: ubuntu-18.04
    steps:
      -
        name: "Checkout release tag"
        uses: actions/checkout@v2
      -
        name: "Setup NVM"
        uses: dcodeIO/setup-node-nvm@master
        with:
          node-version: v12.22.0
      -
        name: "Setup environment"
        run: ./script/setup
      -
        name: "Build pattern-library"
        run: ./script/build
name: build
on: push
